const API_BASE_URL_DEVELOPMENT = "http://localhost:8080";
const API_BASE_PRODUCTION = "";

const ENDPOINTS_DRIVERS = {
  GET_ALL_DRIVERS: "drivers",
  GET_DRIVER_BY_ID:"driver"
};
const ENDPOINTS_USERS = {
    GET_ALL_USERS: "users",
    GET_USER_BY_ID:"user"
  };

  const ENDPOINTS_BRANDS = {
    GET_ALL_BRANDS: "brands",
    GET_BRAND_BY_ID:"brand"
  };

  const ENDPOINTS_MODELS = {
    GET_ALL_MODELS: "models",
    GET_MODEL_BY_ID:"model"
  };

  const ENDPOINTS_VEHICLES = {
    GET_ALL_VEHICLES: "vehicles",
    GET_VEHICLE_BY_ID:"vehicle"
  };

  const ENDPOINTS_ORDERS = {
    GET_ALL_ORDERS: "orders",
    GET_ORDER_BY_ID:"order"
  };
const development = { 
  API_URL_GET_ALL_DRIVERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_DRIVERS.GET_ALL_DRIVERS}`,
  API_URL_GET_DRIVER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_DRIVERS.GET_DRIVER_BY_ID}`,

  API_URL_GET_ALL_BRANDS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_BRANDS.GET_ALL_BRANDS}`,
  API_URL_GET_BRAND_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_BRANDS.GET_BRAND_BY_ID}`,

  API_URL_GET_ALL_MODELS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_MODELS.GET_ALL_MODELS}`,
  API_URL_GET_MODEL_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_MODELS.GET_MODEL_BY_ID}`,

  API_URL_GET_ALL_VEHICLES: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_VEHICLES.GET_ALL_VEHICLES}`,
  API_URL_GET_VEHICLE_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_VEHICLES.GET_VEHICLE_BY_ID}`,

  API_URL_GET_ALL_ORDERS: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_ORDERS.GET_ALL_ORDERS}`,
  API_URL_GET_ORDER_BY_ID: `${API_BASE_URL_DEVELOPMENT}/${ENDPOINTS_ORDERS.GET_ORDER_BY_ID}`,
 
};
const production = {
  API_URL_GET_ALL_VEHICLES: ``,
};
const Constants =
  process.env.NODE_ENV === "development" ? development : production;
export default Constants;
